params_xgb:
  random_state: 42
  objective: 'reg:squarederror'
  eval_metric: 'mape'
  max_depth: 7
  learning_rate: 0.2
  n_estimators: 150
  n_jobs: -1
  colsample_bytree : 0.8
  verbosity: 0
  subsample: 1

# just for showing how to add models
params_rf:
  random_state: 42
  n_estimators: 100
  max_depth: 9
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 'auto'
  bootstrap: True
  oob_score: True
  n_jobs: -1
  verbose: 0
